# zmodload zsh/zprof
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

DISABLE_MAGIC_FUNCTIONS=true
COMPLETION_WAITING_DOTS="true"

HIST_STAMPS="mm/dd/yyyy"

plugins=(
    npm
    osx
    k
    git
    docker-compose
    zsh-autosuggestions
    zsh-syntax-highlighting
    colored-man-pages
)

source $ZSH/oh-my-zsh.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

source ~/.profile
# zprof

export PATH="/usr/local/sbin:$PATH"
alias p4merge='/Applications/p4merge.app/Contents/MacOS/p4merge'
alias compose='docker-compose'
alias kube='kubectl'
alias kls='kubeless'
